services:
  postgres:
    image: postgres:16
    container_name: contact-postgres
    environment:
      POSTGRES_DB: contactdb
      POSTGRES_USER: nuri
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"